//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVentaWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Ventas = new List<Ventas>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public double precio_total { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public List<Ventas> Ventas { get; set; }
    }
}
