//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntoVentaWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int id { get; set; }
        public int id_factura { get; set; }
        public int id_producto { get; set; }
        public double precio { get; set; }
        public int cantidad { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
