//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facturas", Namespace="http://puntoventa7a.gear.host/")]
    [System.SerializableAttribute()]
    public partial class Facturas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int id_clienteField;
        
        private double precio_totalField;
        
        private int diaField;
        
        private int mesField;
        
        private int anioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Clientes ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Ventas[] VentasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double precio_total {
            get {
                return this.precio_totalField;
            }
            set {
                if ((this.precio_totalField.Equals(value) != true)) {
                    this.precio_totalField = value;
                    this.RaisePropertyChanged("precio_total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int dia {
            get {
                return this.diaField;
            }
            set {
                if ((this.diaField.Equals(value) != true)) {
                    this.diaField = value;
                    this.RaisePropertyChanged("dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int mes {
            get {
                return this.mesField;
            }
            set {
                if ((this.mesField.Equals(value) != true)) {
                    this.mesField = value;
                    this.RaisePropertyChanged("mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int anio {
            get {
                return this.anioField;
            }
            set {
                if ((this.anioField.Equals(value) != true)) {
                    this.anioField = value;
                    this.RaisePropertyChanged("anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Interface.WebService.Clientes Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Interface.WebService.Ventas[] Ventas {
            get {
                return this.VentasField;
            }
            set {
                if ((object.ReferenceEquals(this.VentasField, value) != true)) {
                    this.VentasField = value;
                    this.RaisePropertyChanged("Ventas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://puntoventa7a.gear.host/")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Facturas[] FacturasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Interface.WebService.Facturas[] Facturas {
            get {
                return this.FacturasField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturasField, value) != true)) {
                    this.FacturasField = value;
                    this.RaisePropertyChanged("Facturas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ventas", Namespace="http://puntoventa7a.gear.host/")]
    [System.SerializableAttribute()]
    public partial class Ventas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int id_facturaField;
        
        private int id_productoField;
        
        private double precioField;
        
        private int cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Facturas FacturasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Productos ProductosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_factura {
            get {
                return this.id_facturaField;
            }
            set {
                if ((this.id_facturaField.Equals(value) != true)) {
                    this.id_facturaField = value;
                    this.RaisePropertyChanged("id_factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_producto {
            get {
                return this.id_productoField;
            }
            set {
                if ((this.id_productoField.Equals(value) != true)) {
                    this.id_productoField = value;
                    this.RaisePropertyChanged("id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Interface.WebService.Facturas Facturas {
            get {
                return this.FacturasField;
            }
            set {
                if ((object.ReferenceEquals(this.FacturasField, value) != true)) {
                    this.FacturasField = value;
                    this.RaisePropertyChanged("Facturas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Interface.WebService.Productos Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos", Namespace="http://puntoventa7a.gear.host/")]
    [System.SerializableAttribute()]
    public partial class Productos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private double precioField;
        
        private int stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.WebService.Ventas[] VentasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Interface.WebService.Ventas[] Ventas {
            get {
                return this.VentasField;
            }
            set {
                if ((object.ReferenceEquals(this.VentasField, value) != true)) {
                    this.VentasField = value;
                    this.RaisePropertyChanged("Ventas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://puntoventa7a.gear.host/", ConfigurationName="WebService.puntoVentaSoap")]
    public interface puntoVentaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createFactura", ReplyAction="*")]
        int createFactura(int id_cliente, float precio_total, int dia, int mes, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<int> createFacturaAsync(int id_cliente, float precio_total, int dia, int mes, int anio);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento readFacturaResult del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readFactura", ReplyAction="*")]
        Interface.WebService.readFacturaResponse readFactura(Interface.WebService.readFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.readFacturaResponse> readFacturaAsync(Interface.WebService.readFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateFactura", ReplyAction="*")]
        int updateFactura(int id, int id_cliente, float precio_total, int dia, int mes, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateFacturaAsync(int id, int id_cliente, float precio_total, int dia, int mes, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteFactura", ReplyAction="*")]
        int deleteFactura(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteFacturaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createVenta", ReplyAction="*")]
        int createVenta(int id_factura, int id_producto, float precio, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> createVentaAsync(int id_factura, int id_producto, float precio, int cantidad);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento readVentaResult del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readVenta", ReplyAction="*")]
        Interface.WebService.readVentaResponse readVenta(Interface.WebService.readVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.readVentaResponse> readVentaAsync(Interface.WebService.readVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateVenta", ReplyAction="*")]
        int updateVenta(int id, int id_factura, int id_producto, float precio, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateVentaAsync(int id, int id_factura, int id_producto, float precio, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteVenta", ReplyAction="*")]
        int deleteVenta(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteVentaAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createClientes", ReplyAction="*")]
        Interface.WebService.createClientesResponse createClientes(Interface.WebService.createClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.createClientesResponse> createClientesAsync(Interface.WebService.createClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento readClientesResult del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readClientes", ReplyAction="*")]
        Interface.WebService.readClientesResponse readClientes(Interface.WebService.readClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.readClientesResponse> readClientesAsync(Interface.WebService.readClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateClientes", ReplyAction="*")]
        Interface.WebService.updateClientesResponse updateClientes(Interface.WebService.updateClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.updateClientesResponse> updateClientesAsync(Interface.WebService.updateClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteClientes", ReplyAction="*")]
        int deleteClientes(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteClientesAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createProductos", ReplyAction="*")]
        Interface.WebService.createProductosResponse createProductos(Interface.WebService.createProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/createProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.createProductosResponse> createProductosAsync(Interface.WebService.createProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateProductos", ReplyAction="*")]
        Interface.WebService.updateProductosResponse updateProductos(Interface.WebService.updateProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/updateProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.updateProductosResponse> updateProductosAsync(Interface.WebService.updateProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteProductos", ReplyAction="*")]
        int deleteProductos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/deleteProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteProductosAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento readProductosResult del espacio de nombres http://puntoventa7a.gear.host/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readProductos", ReplyAction="*")]
        Interface.WebService.readProductosResponse readProductos(Interface.WebService.readProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://puntoventa7a.gear.host/readProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<Interface.WebService.readProductosResponse> readProductosAsync(Interface.WebService.readProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readFactura", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readFacturaRequestBody Body;
        
        public readFacturaRequest() {
        }
        
        public readFacturaRequest(Interface.WebService.readFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class readFacturaRequestBody {
        
        public readFacturaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readFacturaResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readFacturaResponseBody Body;
        
        public readFacturaResponse() {
        }
        
        public readFacturaResponse(Interface.WebService.readFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class readFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interface.WebService.Facturas[] readFacturaResult;
        
        public readFacturaResponseBody() {
        }
        
        public readFacturaResponseBody(Interface.WebService.Facturas[] readFacturaResult) {
            this.readFacturaResult = readFacturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readVenta", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readVentaRequestBody Body;
        
        public readVentaRequest() {
        }
        
        public readVentaRequest(Interface.WebService.readVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class readVentaRequestBody {
        
        public readVentaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readVentaResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readVentaResponseBody Body;
        
        public readVentaResponse() {
        }
        
        public readVentaResponse(Interface.WebService.readVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class readVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interface.WebService.Ventas[] readVentaResult;
        
        public readVentaResponseBody() {
        }
        
        public readVentaResponseBody(Interface.WebService.Ventas[] readVentaResult) {
            this.readVentaResult = readVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createClientes", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.createClientesRequestBody Body;
        
        public createClientesRequest() {
        }
        
        public createClientesRequest(Interface.WebService.createClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class createClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        public createClientesRequestBody() {
        }
        
        public createClientesRequestBody(string nombres, string apellidos, string direccion, string correo) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.direccion = direccion;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createClientesResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.createClientesResponseBody Body;
        
        public createClientesResponse() {
        }
        
        public createClientesResponse(Interface.WebService.createClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class createClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createClientesResult;
        
        public createClientesResponseBody() {
        }
        
        public createClientesResponseBody(int createClientesResult) {
            this.createClientesResult = createClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readClientes", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readClientesRequestBody Body;
        
        public readClientesRequest() {
        }
        
        public readClientesRequest(Interface.WebService.readClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class readClientesRequestBody {
        
        public readClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readClientesResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readClientesResponseBody Body;
        
        public readClientesResponse() {
        }
        
        public readClientesResponse(Interface.WebService.readClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class readClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interface.WebService.Clientes[] readClientesResult;
        
        public readClientesResponseBody() {
        }
        
        public readClientesResponseBody(Interface.WebService.Clientes[] readClientesResult) {
            this.readClientesResult = readClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateClientes", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.updateClientesRequestBody Body;
        
        public updateClientesRequest() {
        }
        
        public updateClientesRequest(Interface.WebService.updateClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class updateClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        public updateClientesRequestBody() {
        }
        
        public updateClientesRequestBody(int id, string nombres, string apellidos, string direccion, string correo) {
            this.id = id;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.direccion = direccion;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateClientesResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.updateClientesResponseBody Body;
        
        public updateClientesResponse() {
        }
        
        public updateClientesResponse(Interface.WebService.updateClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class updateClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateClientesResult;
        
        public updateClientesResponseBody() {
        }
        
        public updateClientesResponseBody(int updateClientesResult) {
            this.updateClientesResult = updateClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createProductos", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.createProductosRequestBody Body;
        
        public createProductosRequest() {
        }
        
        public createProductosRequest(Interface.WebService.createProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class createProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int stock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        public createProductosRequestBody() {
        }
        
        public createProductosRequestBody(string nombre, double precio, int stock, string descripcion) {
            this.nombre = nombre;
            this.precio = precio;
            this.stock = stock;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createProductosResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.createProductosResponseBody Body;
        
        public createProductosResponse() {
        }
        
        public createProductosResponse(Interface.WebService.createProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class createProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createProductosResult;
        
        public createProductosResponseBody() {
        }
        
        public createProductosResponseBody(int createProductosResult) {
            this.createProductosResult = createProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProductos", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.updateProductosRequestBody Body;
        
        public updateProductosRequest() {
        }
        
        public updateProductosRequest(Interface.WebService.updateProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class updateProductosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int stock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string descripcion;
        
        public updateProductosRequestBody() {
        }
        
        public updateProductosRequestBody(int id, string nombre, double precio, int stock, string descripcion) {
            this.id = id;
            this.nombre = nombre;
            this.precio = precio;
            this.stock = stock;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProductosResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.updateProductosResponseBody Body;
        
        public updateProductosResponse() {
        }
        
        public updateProductosResponse(Interface.WebService.updateProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class updateProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateProductosResult;
        
        public updateProductosResponseBody() {
        }
        
        public updateProductosResponseBody(int updateProductosResult) {
            this.updateProductosResult = updateProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readProductos", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readProductosRequestBody Body;
        
        public readProductosRequest() {
        }
        
        public readProductosRequest(Interface.WebService.readProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class readProductosRequestBody {
        
        public readProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readProductosResponse", Namespace="http://puntoventa7a.gear.host/", Order=0)]
        public Interface.WebService.readProductosResponseBody Body;
        
        public readProductosResponse() {
        }
        
        public readProductosResponse(Interface.WebService.readProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://puntoventa7a.gear.host/")]
    public partial class readProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Interface.WebService.Productos[] readProductosResult;
        
        public readProductosResponseBody() {
        }
        
        public readProductosResponseBody(Interface.WebService.Productos[] readProductosResult) {
            this.readProductosResult = readProductosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface puntoVentaSoapChannel : Interface.WebService.puntoVentaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class puntoVentaSoapClient : System.ServiceModel.ClientBase<Interface.WebService.puntoVentaSoap>, Interface.WebService.puntoVentaSoap {
        
        public puntoVentaSoapClient() {
        }
        
        public puntoVentaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public puntoVentaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public puntoVentaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public puntoVentaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int createFactura(int id_cliente, float precio_total, int dia, int mes, int anio) {
            return base.Channel.createFactura(id_cliente, precio_total, dia, mes, anio);
        }
        
        public System.Threading.Tasks.Task<int> createFacturaAsync(int id_cliente, float precio_total, int dia, int mes, int anio) {
            return base.Channel.createFacturaAsync(id_cliente, precio_total, dia, mes, anio);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.readFacturaResponse Interface.WebService.puntoVentaSoap.readFactura(Interface.WebService.readFacturaRequest request) {
            return base.Channel.readFactura(request);
        }
        
        public Interface.WebService.Facturas[] readFactura() {
            Interface.WebService.readFacturaRequest inValue = new Interface.WebService.readFacturaRequest();
            inValue.Body = new Interface.WebService.readFacturaRequestBody();
            Interface.WebService.readFacturaResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).readFactura(inValue);
            return retVal.Body.readFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.readFacturaResponse> Interface.WebService.puntoVentaSoap.readFacturaAsync(Interface.WebService.readFacturaRequest request) {
            return base.Channel.readFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.readFacturaResponse> readFacturaAsync() {
            Interface.WebService.readFacturaRequest inValue = new Interface.WebService.readFacturaRequest();
            inValue.Body = new Interface.WebService.readFacturaRequestBody();
            return ((Interface.WebService.puntoVentaSoap)(this)).readFacturaAsync(inValue);
        }
        
        public int updateFactura(int id, int id_cliente, float precio_total, int dia, int mes, int anio) {
            return base.Channel.updateFactura(id, id_cliente, precio_total, dia, mes, anio);
        }
        
        public System.Threading.Tasks.Task<int> updateFacturaAsync(int id, int id_cliente, float precio_total, int dia, int mes, int anio) {
            return base.Channel.updateFacturaAsync(id, id_cliente, precio_total, dia, mes, anio);
        }
        
        public int deleteFactura(int id) {
            return base.Channel.deleteFactura(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteFacturaAsync(int id) {
            return base.Channel.deleteFacturaAsync(id);
        }
        
        public int createVenta(int id_factura, int id_producto, float precio, int cantidad) {
            return base.Channel.createVenta(id_factura, id_producto, precio, cantidad);
        }
        
        public System.Threading.Tasks.Task<int> createVentaAsync(int id_factura, int id_producto, float precio, int cantidad) {
            return base.Channel.createVentaAsync(id_factura, id_producto, precio, cantidad);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.readVentaResponse Interface.WebService.puntoVentaSoap.readVenta(Interface.WebService.readVentaRequest request) {
            return base.Channel.readVenta(request);
        }
        
        public Interface.WebService.Ventas[] readVenta() {
            Interface.WebService.readVentaRequest inValue = new Interface.WebService.readVentaRequest();
            inValue.Body = new Interface.WebService.readVentaRequestBody();
            Interface.WebService.readVentaResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).readVenta(inValue);
            return retVal.Body.readVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.readVentaResponse> Interface.WebService.puntoVentaSoap.readVentaAsync(Interface.WebService.readVentaRequest request) {
            return base.Channel.readVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.readVentaResponse> readVentaAsync() {
            Interface.WebService.readVentaRequest inValue = new Interface.WebService.readVentaRequest();
            inValue.Body = new Interface.WebService.readVentaRequestBody();
            return ((Interface.WebService.puntoVentaSoap)(this)).readVentaAsync(inValue);
        }
        
        public int updateVenta(int id, int id_factura, int id_producto, float precio, int cantidad) {
            return base.Channel.updateVenta(id, id_factura, id_producto, precio, cantidad);
        }
        
        public System.Threading.Tasks.Task<int> updateVentaAsync(int id, int id_factura, int id_producto, float precio, int cantidad) {
            return base.Channel.updateVentaAsync(id, id_factura, id_producto, precio, cantidad);
        }
        
        public int deleteVenta(int id) {
            return base.Channel.deleteVenta(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteVentaAsync(int id) {
            return base.Channel.deleteVentaAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.createClientesResponse Interface.WebService.puntoVentaSoap.createClientes(Interface.WebService.createClientesRequest request) {
            return base.Channel.createClientes(request);
        }
        
        public int createClientes(string nombres, string apellidos, string direccion, string correo) {
            Interface.WebService.createClientesRequest inValue = new Interface.WebService.createClientesRequest();
            inValue.Body = new Interface.WebService.createClientesRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.direccion = direccion;
            inValue.Body.correo = correo;
            Interface.WebService.createClientesResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).createClientes(inValue);
            return retVal.Body.createClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.createClientesResponse> Interface.WebService.puntoVentaSoap.createClientesAsync(Interface.WebService.createClientesRequest request) {
            return base.Channel.createClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.createClientesResponse> createClientesAsync(string nombres, string apellidos, string direccion, string correo) {
            Interface.WebService.createClientesRequest inValue = new Interface.WebService.createClientesRequest();
            inValue.Body = new Interface.WebService.createClientesRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.direccion = direccion;
            inValue.Body.correo = correo;
            return ((Interface.WebService.puntoVentaSoap)(this)).createClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.readClientesResponse Interface.WebService.puntoVentaSoap.readClientes(Interface.WebService.readClientesRequest request) {
            return base.Channel.readClientes(request);
        }
        
        public Interface.WebService.Clientes[] readClientes() {
            Interface.WebService.readClientesRequest inValue = new Interface.WebService.readClientesRequest();
            inValue.Body = new Interface.WebService.readClientesRequestBody();
            Interface.WebService.readClientesResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).readClientes(inValue);
            return retVal.Body.readClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.readClientesResponse> Interface.WebService.puntoVentaSoap.readClientesAsync(Interface.WebService.readClientesRequest request) {
            return base.Channel.readClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.readClientesResponse> readClientesAsync() {
            Interface.WebService.readClientesRequest inValue = new Interface.WebService.readClientesRequest();
            inValue.Body = new Interface.WebService.readClientesRequestBody();
            return ((Interface.WebService.puntoVentaSoap)(this)).readClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.updateClientesResponse Interface.WebService.puntoVentaSoap.updateClientes(Interface.WebService.updateClientesRequest request) {
            return base.Channel.updateClientes(request);
        }
        
        public int updateClientes(int id, string nombres, string apellidos, string direccion, string correo) {
            Interface.WebService.updateClientesRequest inValue = new Interface.WebService.updateClientesRequest();
            inValue.Body = new Interface.WebService.updateClientesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.direccion = direccion;
            inValue.Body.correo = correo;
            Interface.WebService.updateClientesResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).updateClientes(inValue);
            return retVal.Body.updateClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.updateClientesResponse> Interface.WebService.puntoVentaSoap.updateClientesAsync(Interface.WebService.updateClientesRequest request) {
            return base.Channel.updateClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.updateClientesResponse> updateClientesAsync(int id, string nombres, string apellidos, string direccion, string correo) {
            Interface.WebService.updateClientesRequest inValue = new Interface.WebService.updateClientesRequest();
            inValue.Body = new Interface.WebService.updateClientesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.direccion = direccion;
            inValue.Body.correo = correo;
            return ((Interface.WebService.puntoVentaSoap)(this)).updateClientesAsync(inValue);
        }
        
        public int deleteClientes(int id) {
            return base.Channel.deleteClientes(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteClientesAsync(int id) {
            return base.Channel.deleteClientesAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.createProductosResponse Interface.WebService.puntoVentaSoap.createProductos(Interface.WebService.createProductosRequest request) {
            return base.Channel.createProductos(request);
        }
        
        public int createProductos(string nombre, double precio, int stock, string descripcion) {
            Interface.WebService.createProductosRequest inValue = new Interface.WebService.createProductosRequest();
            inValue.Body = new Interface.WebService.createProductosRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.descripcion = descripcion;
            Interface.WebService.createProductosResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).createProductos(inValue);
            return retVal.Body.createProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.createProductosResponse> Interface.WebService.puntoVentaSoap.createProductosAsync(Interface.WebService.createProductosRequest request) {
            return base.Channel.createProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.createProductosResponse> createProductosAsync(string nombre, double precio, int stock, string descripcion) {
            Interface.WebService.createProductosRequest inValue = new Interface.WebService.createProductosRequest();
            inValue.Body = new Interface.WebService.createProductosRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.descripcion = descripcion;
            return ((Interface.WebService.puntoVentaSoap)(this)).createProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.updateProductosResponse Interface.WebService.puntoVentaSoap.updateProductos(Interface.WebService.updateProductosRequest request) {
            return base.Channel.updateProductos(request);
        }
        
        public int updateProductos(int id, string nombre, double precio, int stock, string descripcion) {
            Interface.WebService.updateProductosRequest inValue = new Interface.WebService.updateProductosRequest();
            inValue.Body = new Interface.WebService.updateProductosRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.descripcion = descripcion;
            Interface.WebService.updateProductosResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).updateProductos(inValue);
            return retVal.Body.updateProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.updateProductosResponse> Interface.WebService.puntoVentaSoap.updateProductosAsync(Interface.WebService.updateProductosRequest request) {
            return base.Channel.updateProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.updateProductosResponse> updateProductosAsync(int id, string nombre, double precio, int stock, string descripcion) {
            Interface.WebService.updateProductosRequest inValue = new Interface.WebService.updateProductosRequest();
            inValue.Body = new Interface.WebService.updateProductosRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.descripcion = descripcion;
            return ((Interface.WebService.puntoVentaSoap)(this)).updateProductosAsync(inValue);
        }
        
        public int deleteProductos(int id) {
            return base.Channel.deleteProductos(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteProductosAsync(int id) {
            return base.Channel.deleteProductosAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Interface.WebService.readProductosResponse Interface.WebService.puntoVentaSoap.readProductos(Interface.WebService.readProductosRequest request) {
            return base.Channel.readProductos(request);
        }
        
        public Interface.WebService.Productos[] readProductos() {
            Interface.WebService.readProductosRequest inValue = new Interface.WebService.readProductosRequest();
            inValue.Body = new Interface.WebService.readProductosRequestBody();
            Interface.WebService.readProductosResponse retVal = ((Interface.WebService.puntoVentaSoap)(this)).readProductos(inValue);
            return retVal.Body.readProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Interface.WebService.readProductosResponse> Interface.WebService.puntoVentaSoap.readProductosAsync(Interface.WebService.readProductosRequest request) {
            return base.Channel.readProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Interface.WebService.readProductosResponse> readProductosAsync() {
            Interface.WebService.readProductosRequest inValue = new Interface.WebService.readProductosRequest();
            inValue.Body = new Interface.WebService.readProductosRequestBody();
            return ((Interface.WebService.puntoVentaSoap)(this)).readProductosAsync(inValue);
        }
    }
}
